### ISSUE TITLE
黄色連打の描画順の不具合

### ISSUE THREAD

**Issue by HakozakiSerika** [AioiLight/TJAPlayer3#100]
BPMの基本値より高い値(#BPMCHAGEによる)での黄色連打の描画順がおかしい
例
BPM:70
11115558,
11555580, //ここまでは正常
#BPMCHANGE 140
#SCROLL 0.5
11115558,
11555580, //これが見た目の速さは同じだが黄色連打の描画順がおかしくなる

なお風船連打については今のところ異常はなさそうだが要検証

**Comment by AioiLight** [comment]
発声時刻で条件分岐させるようにしたので、正常になりました。
今後COURSE:Towerではスクロールにさせるようにします。
