### ISSUE TITLE
短い黄色連打の表示がおかしくなる

### ISSUE THREAD

**Issue by AioiLight** [AioiLight/TJAPlayer3#135]
ダンガンノーツ'(表)などで確認。
先頭の描画より左にはみ出てしまうので、そこの調整をする。
ついでに先頭の顔と連打部分の切り離しもして、色変化も実装する(つら)。

**Comment by romyu** [comment]
一応PR#145で対応させてみた。
問題になるのはSympleStyleの画像の作り直しになると思われる。

**Comment by AioiLight** [comment]
対応させられたのでクローズ。
