### ISSUE TITLE
場面切り替えのFIFOが目に悪い

### ISSUE THREAD

**Issue by romyu** [AioiLight/TJAPlayer3#179]
特に選曲画面に入る場面、白フェードアウト→黒フェードインなど、あんまり目によろしくないと思われる。

改善案としては、全てフェードカラーを統一する、フェードアニメを太鼓の達人CSの、Wii/WiiU、PS4/NSのような方式にする、切り替え時に、画面真っ暗の空白の時間を与える(いわゆる太鼓の達人AC方式)などが考えられる。

**Comment by AioiLight** [comment]
#155 とかぶってるのでクローズします
