### ISSUE TITLE
段位認定モード不具合シリーズ(謎)

### ISSUE THREAD

**Issue by romyu** [AioiLight/TJAPlayer3#225]
・演奏速度を上昇させると、Sectionアニメ中に譜面が流れてくる。
・完走モードと共存できる。
・スコアモード変化を非対応にすべき(スコアが条件のとき大問題)
・2Pプレイ可能(なお段位判定は1Pのみ)しかも時によっては落ちる。
・アドリブ音符の問題
・最初のセクション演出の前に右上の曲名表示がある(コレは単なる好み)

**Comment by AioiLight** [comment]
個別にissueを立てるのでクロース。
