### ISSUE TITLE
段位道場で一曲目しか読み込まない

### ISSUE THREAD

**Issue by Roriachan** [AioiLight/TJAPlayer3#229]
段位道場(ver1.5.0)で三曲設定の自作段位を作ったけど一曲目しか読み込まない

1.作る
2.再生する
3.何故か残り音符数が一曲目の最大コンボ数になる
4.当然不合格

自分のtjaに異常ないと思いますけどね（ありましたらすいません）

譜面とスクショ貼っときますね
https://ux.getuploader.com/Roria_humen/download/4
pass:error

OS:Windows10 64bit
CPU:intel core i3
メモリ:4GB
バージョン:1.5.0

何かあれば@SevenXa___にご連絡ください。
もしtjaに異常あれば連絡ください。そしてこのバグ報告も消しちゃっていいです。

**Comment by AioiLight** [comment]
解決したようなのでクローズします。
