### ISSUE TITLE
JPOSSCROLLを使用すると、飛んでいく音符のスタート位置が次の曲以降に引き継がれる

### ISSUE THREAD

**Issue by rhimm** [AioiLight/TJAPlayer3#237]
JPOSSCROLLが含まれる譜面をプレイし、終了したときに判定枠がデフォルト位置から移動していた場合、飛んでいく音符が前回終了したときに判定枠があった位置から飛んでいく。

①JPOSSCROLLで判定枠が移動する曲を選択し、プレイ（もしくはオート再生）
![20181221224202](https://user-images.githubusercontent.com/40219006/50345360-1a781a00-0572-11e9-9692-da6e179e562a.png)
②Escキーでも、曲の終了でもいいので、判定枠がデフォルト位置から移動しているタイミングで演奏画面から離れる
③適当な曲を選択する（JPOSSCROLLを含まない譜面がわかりやすい）
④こうなる（前回終了時の判定枠があった、デフォルト位置の少し右から音符が飛んでいっている）
![20181221224309](https://user-images.githubusercontent.com/40219006/50345416-57dca780-0572-11e9-921c-21053a1cef87.png)
![20181221224307](https://user-images.githubusercontent.com/40219006/50345432-67f48700-0572-11e9-956b-0ee89be9b0f0.png)

備考：Game_Effect_FlyingNotes_IsUsingEasingの値を0にしても1にしてもなります。

**Comment by AioiLight** [comment]
SkinConfigをそのまま変更してる()のでそれを直す必要性がありますね。とメモ。

**Comment by AioiLight** [comment]
直したのでクローズ。
