### ISSUE TITLE
Languages with decimal comma

### ISSUE THREAD

**Issue by kuu22** [AioiLight/TJAPlayer3#27]
I have my system language set to Spanish where we use `,` instead of `.` to write decimals (for example `1,05` instead of `1.05`. C# parses them according to the system language.
The  issue is, all .tja files are written with `.` as a decimal, so, for example, `OFFSET:-4.3` is read as `-43`, making it unplayable. This happens on all versions of TJAPlayer.
Adding 
```cs
CultureInfo.DefaultThreadCurrentCulture = CultureInfo.InvariantCulture;
```
or
```cs
Thread.CurrentThread.CurrentCulture = CultureInfo.InvariantCulture;
``` 
to Main in [Program.cs](https://github.com/AioiLight/TJAPlayer3/blob/master/DTXMania%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88/%E3%82%B3%E3%83%BC%E3%83%89/%E5%85%A8%E4%BD%93/Program.cs) should fix the problem.

**Comment by AioiLight** [comment]
e78c8c4d9674d1621e49e06627bf51b6590d63ca has been fixed. Thank you reporting!
