### ISSUE TITLE
段位記述時に曲名にカンマが入るとややこしい。

### ISSUE THREAD

**Issue by miyaneko1467** [AioiLight/TJAPlayer3#270]
全角にすればいいやん！とか思うけど、あまり気付きにくい問題だと思った。

**Comment by AioiLight** [comment]
エスケープさせれば解決しますね。

**Comment by AioiLight** [comment]
afe1f77413073d1f3a0e9c867be6b407e8ac4925 で独自のエスケープ処理を実装しました。`\,` と記述することで、実際に半角カンマを表示することができるようになります。
