### ISSUE TITLE
TJAP3が消去されたら、TCDNを消去します。

### ISSUE THREAD

**Issue by Moriumi** [AioiLight/TJAPlayer3#273]

**Comment by AioiLight** [comment]
じゃあTJAP3を消して残ってる最新のブランチから新しいシミュレータを作ります？それでいいですか？

**Comment by Moriumi** [comment]
TJAP3リポジトリ消すんですね？
あと名前変えるんですね？

**Comment by AioiLight** [comment]
それでいいなら結構ですよ

**Comment by Moriumi** [comment]
いいですよ、じゃあ消してください。

**Comment by Moriumi** [comment]
現在配布している今までのバージョンも消してくださいね。

**Comment by Moriumi** [comment]
いつできますか

**Comment by AioiLight** [comment]
配布しているバージョンってGitHubとは無関係なんですけど
ふざけてるんですか？

**Comment by Moriumi** [comment]
はぁ？

**Comment by Moriumi** [comment]
TJAP3を消すんですよね

**Comment by Moriumi** [comment]
配布しているバージョンはTJAP3ですよね
そっちこそふざけてるんですか

**Comment by romyu** [comment]
Moriumi
アンケートで決まったことなのでさっさと消せ。

**Comment by Moriumi** [comment]
いまAioiさんと話してるんですけど

**Comment by Moriumi** [comment]
貴方の意見は聞いてないです

**Comment by romyu** [comment]
消せ

**Comment by Moriumi** [comment]
だからあなたと話してないです

**Comment by romyu** [comment]
割り込んででなにか悪いんですか？
人の話を無視した人が言えることじゃないです、

**Comment by Moriumi** [comment]
で、提案に乗るんですか。乗らないんですか。

**Comment by romyu** [comment]
人の話を聞きましょうね
Moriumi さん。
わたしはあなたにむしをされたからあなたのしじにしたがうひつようはないんですよ　。

**Comment by Moriumi** [comment]
なら好きなだけ一人で話していてください。

**Comment by Skymint2270** [comment]
醜いなぁ...

**Comment by AioiLight** [comment]
じゃあTJAP3のミラーサイトを作ってそこで配布を続けます。オープンソースなので問題ないですよね？いいですか？

**Comment by Moriumi** [comment]
ん？

**Comment by Moriumi** [comment]
TJAP3が消去されたらの意味わかってますか？日本語。

**Comment by Moriumi** [comment]
最初といってること違うけど大丈夫ですかぁ～？

**Comment by AioiLight** [comment]
いやMITライセンス守ってるなら何したって問題ないでしょう？まさか今あるミラーまで消せというのですか？

**Comment by Moriumi** [comment]
んー

**Comment by Moriumi** [comment]
じゃあミラーはいいです。

**Comment by Moriumi** [comment]
このリポとAioilight.spaceからの削除、それでいいですか

**Comment by AioiLight** [comment]
名称変更もありっておっしゃいましたよね？

**Comment by Moriumi** [comment]
あぁ

**Comment by Moriumi** [comment]
話止めます、お疲れさまでした。

**Comment by Moriumi** [comment]
頑張って消しましょうね。

**Comment by AioiLight** [comment]
本当に消すわけねぇだろ int.MaxValue年ＲＯＭってろ
