### ISSUE TITLE
DP時、コンボボイスが鳴ったり鳴らなかったりする。

### ISSUE THREAD

**Issue by miyaneko1467** [AioiLight/TJAPlayer3#276]
どちらも同じコンボ数でないと鳴ったり鳴らなかったりする(規則性が不明)
どちらかがずっとミスし続けると50コンボ以降は鳴らない。

**Comment by Seseragi255** [comment]
Pull request #277 にて修正いたしました。
原因は、片プレイヤーがミスをしたときに、もう一方のプレイヤーのVoiceIndexも同時にリセットされてしまうためでした。
Pull request #277 では、プレイヤーを参照するようにして解決しました。

**Comment by miyaneko1467** [comment]
あいおいさんが承認され次第クローズします。

**Comment by miyaneko1467** [comment]
232c02b で解消済みなので閉じます。
