### ISSUE TITLE
次郎にあるような小節線移動機能

### ISSUE THREAD

**Issue by Moriumi** [AioiLight/TJAPlayer3#295]

**Comment by romyu** [comment]
あなたが望ようなのでリクエストやめますね。
他の人頑張ってくださいな。

**Comment by Moriumi** [comment]
あなたのその判断で誰が得をするんですかね。

**Comment by Moriumi** [comment]
まぁあなたは今まで沢山の時間をTJAP3に裂き、貢献してきました。もしあなたがTJAP3と縁を切るといっても、リクエストを送らないといっても、誰も文句はないでしょう。今までお疲れさまでした。

**Comment by Moriumi** [comment]
僕はTJAP3をもっとよくしたいという思いでPRを送ったりIssueを開いたりしました。その思いが伝わらなかったようで残念です。

**Comment by Moriumi** [comment]
あなた以外に小節線移動を実装する人はいないでしょうね。

**Comment by Moriumi** [comment]
余計なことをして本当に申し訳ありませんでした。

**Comment by Moriumi** [comment]
この機能を楽しみにしていた方にも、お詫び申し上げます。。
