### ISSUE TITLE
時々ウィンドウが古くなる

### ISSUE THREAD

**Issue by miyaneko1467** [AioiLight/TJAPlayer3#312]
Windows10のウィンドウからいきなりWindows7あたりになる

**Comment by AioiLight** [comment]
情報が不十分です
どのWindows10のバージョンなのか、どのGPUとドライバーを使っているのか、
MacTypeやClassicShellなどのシステムを書き換えするアプリを使っているかどうか否かを教えてください。
また、デスクトップコンポジションを無効にしてる場合はそうなる可能性があります。

**Comment by miyaneko1467** [comment]
情報が不十分なため、閉めます。
