### ISSUE TITLE
DP時に判定がおかしくなる

### ISSUE THREAD

**Issue by myuu931** [AioiLight/TJAPlayer3#316]
**Describe the bug**
DP時に判定がおかしくなる

**To Reproduce**
2人プレイを有効にする

**Expected behavior**
判定枠を超えた後のノーツの判定が無くなる

**Desktop (please complete the following information):**
Windows10 Pro 64bit
CPU : Intel Core i5-3320M
RAM : 8GB

**Additional context**
他の人も同じような現象が起きているそうです

**Comment by AioiLight** [comment]
a625505ae3808e5e2b5f44491784716b7a1e4900 で修正されました。

**Comment by AioiLight** [comment]
修正済み。
