### ISSUE TITLE
The notes after the Kusudama ball cannot be hitten

### ISSUE THREAD

**Issue by wehnes** [AioiLight/TJAPlayer3#317]
**Describe the bug**
(バグについての説明を書いてください)

The notes after the Kusudama ball can't be hitten when finish all of the Kusudama ball. If you don't finish it, the bug won't happen.  

**Desktop (please complete the following information):**
(バグが起こったPC環境を書いてください)
System: Windows 10 Pro 64bit, 1511
CPU: Intel Core i5 3210M
RAM: 8GB

**Comment by wehnes** [comment]
I'm sorry that I forget report the version of tjap3. The version is 1.5.5

**Comment by AioiLight** [comment]
くす玉音符は未実装で、すべてふうせん連打に置き換わってるはずだと思いますが、くす玉音符で本当に正しいですか？
I think it is supposed to be replaced with a balloon hit, but it is really correct with a kusudama note?

**Comment by wehnes** [comment]
It looks like a balloon… I don't know how to say it in English correctly. Maybe I mean if the balloon notes are all hit, then I cannot hit the notes after it.

**Comment by AioiLight** [comment]
それはパソコンを再起動しても直りませんか?
Will not it fix even if you reboot your PC?

**Comment by wehnes** [comment]
I try it and it really works! I used to shut it down but I never try to reboot it. Thank you for your advise.
