### ISSUE TITLE
コンフィグ画面を出ると急に音がでかくなる

### ISSUE THREAD

**Issue by elizanan44** [AioiLight/TJAPlayer3#333]
コンフィグ画面でBGMやSoundEffectやVoiceの音量を下げても、コンフィグ画面を出ると、BGM,SoundEffect,Voiceの音量がでかくなる又、Voiceの音量も0にしても再生される

**Comment by AioiLight** [comment]
こちらの環境では再現できませんでした。

使用しているバージョン、コンピュータの環境、使用しているオーディオ機器の環境を書いてください。

**Comment by elizanan44** [comment]
使用バージョン Ver.1.5.5 コンピュータの環境 Windows10 32bit オーディオ WASAPI
