### ISSUE TITLE
難易度ごとに魂ゲージの画像が変わるようにしたいです

### ISSUE THREAD

**Issue by ryokusei2175** [AioiLight/TJAPlayer3#335]
難易度によってゲージを変えたいです
（oniならいつも通り、
hard,normalではクリアの文字、黄色い部分がoniより５目盛ほど左、
easyなら10目盛ほど左、
danならクリアの文字を出さず、ゲージは赤だけ、
towerなら別のもの/表示なしといったように）
が、クリア文字の表示の有無や位置といった処理を、難易度ごとに分岐するのは可能なのでしょうか...？
もし可能であれば、処理しているところの名前を教えていただけませんか？

クリア基準に達しているかいないかで背景が変化するみたいなので、テクスチャだけでは違和感があると思いました。

**Comment by AioiLight** [comment]
bIsAlreadyCleared、bIsAlreadyMaxed というフィールドでクリアしているか否かを判断しているので、そこのクリア判定を各難易度に置き換えることでお望みの動作を実現することができると思います。
ただ、これは僕が追加した分のコードしかこれを使用していないので、fork元が実装している箇所については未だ魂ゲージ80%に達したかどうかで判断しているモノもあると思うのでそこは適宜置き換えてください

**Comment by AioiLight** [comment]
画像周りでは単純に難易度で表示するゲージの画像を変えれば良いと思います。

**Comment by ryokusei2175** [comment]
ありがとうございます。

**Comment by ryokusei2175** [comment]
クリア文字はテクスチャファイルで消すことでうまく非表示にできました。
次に、コースシンボルのテクスチャの定義
（Difficulty.Totalで指定された値に対応する文字列の操作など）
と同じように画像を変える形でコードをいじってみましたが
正常に反映はされず、「easy」時のテクスチャのみが表示されました。
定義の跡に描画という流れなら、描画指定時もコースシンボルと同じ形式にする必要があると思い、
描画の仕方を定義されている（上半分のゲージと下半分のクリア文字といったような）フィールドや、選択された曲の難易度を処理されている地点などを調べ、探しましたが見つかりませんでした。

**Comment by AioiLight** [comment]
描画のメソッドについてはFDK19.CTexture 辺りだと思います
テクスチャ自体のオブジェクトは TJAPlayer3.TextureLoader にほとんどあります。

**Comment by ryokusei2175** [comment]
希望のシステムを実装でき、問題なく動作させることができました。
教えてくださり本当にありがとうございます。m(__)m
