### ISSUE TITLE
難易度に合わせて魂ゲージ...続き

### ISSUE THREAD

**Issue by ryokusei2175** [AioiLight/TJAPlayer3#336]
#335 より教えていただいたとおりにコードを変えようとしましたが、演奏中の難易度を処理しているところ（現在プレイ中の難易度を暗示しているモノ）が明確にわからなくて、コースシンボルの処理の通りに組みました。すると、「Easy」だけしか映らなくなってしまいました（全難易度に「Easy」時の画像）。
2Pの場合にも適用したいのですが、このまま組むと2Pのゲージが1Pのものと同じになってしまいます。

**Comment by AioiLight** [comment]
詳細な情報が無いのでこちらでもよく分かりません。
あと同じようなissueを立ち上げるのをやめてください。(もし、続きのコメントがあるのであれば #335 でお願いします。)
