### ISSUE TITLE
魂ゲージがノルマ乗ったときの自動フラッシュ

### ISSUE THREAD

**Issue by ryokusei2175** [AioiLight/TJAPlayer3#338]
クリアラインまでゲージが行った時の、赤ゲージが等間隔で黄色く光る機能があったら印象強そうです。

**Comment by romyu** [comment]
グラフィック面の強化は個人で自力でおこなってください。
もうバイナリのファイルはないので、そういうグラフィック面強化の提案や個人改造の質問は控えていただければと思います。
また、本家に寄せる行為は著作権法に関わりますので、自己責任でおこなってください。周りを巻き込まないでください。
