### ISSUE TITLE
演奏速度の仕様変更

### ISSUE THREAD

**Issue by elizanan44** [AioiLight/TJAPlayer3#339]
演奏速度がx1.000以下、以上の場合スロー再生、早送りになるので、音源は再生させないでx1.000のみ音源を再生させるようにしたい。

**Comment by AioiLight** [comment]
音源音量を0にすることでもご要望の動作が期待できますがいかがでしょうか。

**Comment by elizanan44** [comment]
すみません。特訓モードみたいな仕組みにしたいのですができませんでしょうか？

**Comment by AioiLight** [comment]
演奏画面中に再生速度を変えることは現時点ではできませんね
