### ISSUE TITLE
あなたは、android用のバージョンを作成する?

### ISSUE THREAD

**Issue by LuisFellp** [AioiLight/TJAPlayer3#344]

**Comment by AioiLight** [comment]
「Android用のバージョン」を私が作成することはありません。

主な理由として

* .NET C#なコードからC++、Javaにコンバートするのに手間が掛かること
* ユーザーはファイル管理の知識を持つ必要があること
* "作成した譜面を"再生するためにスマートフォンである必要がない

があります。

**Comment by LuisFellp** [comment]
回答ありがとうございます。それは悲しいですね。
