### ISSUE TITLE
SoundDecoder.dll cannot open Unicode filenames

### ISSUE THREAD

**Issue by mon** [AioiLight/TJAPlayer3#35]
Hello, I am on an English system, and the sound decoder cannot open the Japanese filenames. The C# side sends a Unicode (or maybe UTF16?) path and SoundDecoder uses fopen_s, which only takes ANSI.

Is there source code for SoundDecoder.dll? I could not find it... If not, you could use `GetShortPathName` to change the Japanese name to 8.3 (ANSI compatible) before calling SoundDecoder.dll.

If you would like to use `GetShortPathName` I can write a pull request.

**Comment by AioiLight** [comment]
Thank you issuing.
If you okay, please pull request.

**Comment by AioiLight** [comment]
I change path of images. So default skin is not working...
I'll make new default skin soon.

**Comment by AioiLight** [comment]
I made default skin. please check it.

**Comment by mon** [comment]
Hmmmm...
New skin works great, but I can no longer replicate the issue. It seems some other commit may have fixed the issue.  I guess this is a good thing, but still confusing.
