### ISSUE TITLE
Converting to double error

### ISSUE THREAD

**Issue by Daviziu** [AioiLight/TJAPlayer3#39]
Hello, 
I am a big fan of TJAPlayer3!

While creating a .tja file I noticed that the `DEMOSTART` command didn't work correctly. I looked into the CDTX.cs file and noticed that the conversion to double values is locale dependent. In order to fix this you could convert to double using the InvariantCulture like this:
```c#
Convert.ToDouble("12.6", System.Globalization.CultureInfo.InvariantCulture)
```

I am on a German PC, where we use a comma instead of a dot for decimals, so `Convert.ToDouble("12.6")` (without the second argument) returns `126` and not `12.6`.

But **with** `CultureInfo.InvariantCulture` it will be correct for every PC regardless of their locale.

**Comment by AioiLight** [comment]
Thank you for reporting.
I wil install other languages Windows to check this problem. so, please wait a little.
