### ISSUE TITLE
Discordにプレイ中の.tjaファイルを表示する

### ISSUE THREAD

**Issue by AioiLight** [AioiLight/TJAPlayer3#43]
Discordにプレイ中の.tjaファイルを表示したりプレイ時間を出したりする。

**Comment by AioiLight** [comment]
DiscordManagerというクラスを作り、CDTXMania上で実体化してやる。
DiscordManagerでは
``Create();``、``Update();``、``Disconnect();`` メソッドを用意し、起動時、終了時は必ずそれらのメソッドを呼び出す。
(特に切断時はしっかり呼び出しておかないと、Discordでずっとプレイしていることになるらしい。)
シーンの移動時に適当なメッセージととともにUpdateしてやる。
GitHubにDiscord公式のDLLがあるのでそれを入れてやる必要もある。

**Comment by moriumi** [comment]
これ閉じれますね

**Comment by AioiLight** [comment]
閉じました
