### ISSUE TITLE
謎のキャンセル効果音

### ISSUE THREAD

**Issue by romyu** [AioiLight/TJAPlayer3#50]
【内容】
演奏画面でShift+F1を押すと、メニューが開くが、淵の効果音に加えて、何故かキャンセルの効果音が鳴る。

**Comment by AioiLight** [comment]
こちらでは状況再現ができました、どのような環境でできるか教えてくれれば幸いです

**Comment by romyu** [comment]
演奏画面でF1を押すと、小さいポーズ画面が表示されます。その際、通常は縁の効果音「だけ」が鳴ります。この小さいポーズ画面の表示をF1+Shiftで行うと、通常鳴る縁の効果音に加えて、キャンセル効果音が鳴ります。
演奏画面であれば、基本いつでも起こるものだと思われます。
F1+Shiftのショートカットキーは、選曲画面で設定画面へ移動する動作で使われています。その移動の際にキャンセル効果音が鳴ります。それが何かしら影響しているのかも.....しれません。

**Comment by AioiLight** [comment]
選曲画面の非活性化がうまくできてないのか、演奏画面でそのキーに割当がされてるかのどちからと。
ご報告ありがとうございます。
