### ISSUE TITLE
Explosion.pngの下半分が使われていない問題

### ISSUE THREAD

**Issue by romyu** [AioiLight/TJAPlayer3#53]
大音符用エフェクトを移植したのに、反応しなかったことから判明。.

**Comment by romyu** [comment]
検証を行ったので、参考になれば....
https://www.youtube.com/watch?v=4JXuQkK4VgI

**Comment by romyu** [comment]
プルリクエスト
832fc31
にて修正済み

**Comment by AioiLight** [comment]
5995dc236cc5ed335422e88e9b5507505667f166 のPRで修正済。
