### ISSUE TITLE
F2キーを押した時の効果音の多重と無駄に下に動く動作の改善

### ISSUE THREAD

**Issue by HakozakiSerika** [AioiLight/TJAPlayer3#59]
優先度は低くてOK

**Comment by AioiLight** [comment]
すいません、下に無駄に動く、とはどういうステージでいつ起きるものなんでしょうか…？

**Comment by HakozakiSerika** [comment]
曲選択画面でF2を押すと演奏オプションなどのメニューが出てくると思うのですが押した時に1番上のカーソルではなく上から2番目にカーソルが来てしまう(メニューを開く動作としたにカーソルを動かす動作がF2に結びついてしまっていると思われる)ことです。

**Comment by AioiLight** [comment]
これはプログラム上の開始位置の問題ですでに初期位置を0に指定されているためクローズします。
