### ISSUE TITLE
選曲画面での音源ロード中は操作を受け付けない

### ISSUE THREAD

**Issue by romyu** [AioiLight/TJAPlayer3#61]
選曲画面の曲再生待機タイマー終了後、曲がロードし終わるまでの間、操作を受け付けない。
選曲画面での曲再生待機タイマーを短く(100以内ぐらい)するとわかりやすい。
改善はすべきだが、対処法が

**Comment by romyu** [comment]
見つかれば再度通知する。

**Comment by AioiLight** [comment]
曲ロードで時間がかかるのはDirectSoundを使用しているときに起こります。
WASAPI/ASIOでは遅延しないままロードするので、DirectSoundの仕様かと。
非同期処理で曲を読み込むようにすれば、DirectSoundでも固まらないようにできます。
