### ISSUE TITLE
ランナーの描画順

### ISSUE THREAD

**Issue by romyu** [AioiLight/TJAPlayer3#62]
ランナーの描画順が、キャラのパターンの順番に依存している。
本家の場合、出現順に描画をしている。

**Comment by AioiLight** [comment]
パターン順ではなく、使用している配列のインデックス順に描画しています。
現在の方式では0～127の中で「使用中でない」最小のインデックスに現在出現したものを記憶させているため、このような不具合が起きているようです。
"とりあえずは"記憶する場所を順番で127まで進めて、127が埋まったら0に戻すという処理にしようかと考えています。こうすることで127番と0番の描画順がおかしいだけで済みます。
(本来は、先入れ先出しですべきですが...)

**Comment by AioiLight** [comment]
4b652cbdde929175dd5ef197cbf91eddc52bce9c で仮実装。
近い内にリスト形式にする予定です。
