### ISSUE TITLE
初期設定のまま動作しない

### ISSUE THREAD

**Issue by AioiLight** [AioiLight/TJAPlayer3#74]
Config.iniを削除し、ソフト側で再生成したデフォルト設定で動作しない。

現在キャラ関連でコケてるが、他にもエラーで落ちる要素アリ。

要修正（最優先）。

**Comment by romyu** [comment]
テコ入れをするのであれば、サウンドの初期状態をDirectSoundにすると良いと思われる

**Comment by AioiLight** [comment]
WindowsVista以降は自動的にWASAPIに変更され、それ以外はDSoundになるようです。
DirectSoundにするメリットがあまりないので、このままになるかと。

初期設定で落ちることはなくなったが、また再発することも考えられるので基本的にクローズはしない。

**Comment by AioiLight** [comment]
かなり前に修正済み。
